import mongoose from "mongoose";

const clientSchema = new mongoose.Schema({
    clientName:{
        type:String,
        require:true,
    },
    planType:{
        type:String,
        default:"single"
    },
    clientDomain:{
        type:String,
        default:null
    },
    planDuration:{
        type:Date,
        default:null
    },
    freeTrial:{
        type:Boolean,
        default:true
    },
    freeTrialDays:{
        type:Number,
        default:7
    },
    adminUser:{
        id:{
            type:String,
            default:null,
        },
        name:{
            type:String,
            default:null,
        },
        role:{
            type:String,
            default:"admin",
        },
        avatar:{
            type:String,
            default:null
        },
        email:{
            type:String,
            default:null
        }
    },
    platforms:[
        {
            platformName:{
                type:String,
                default:null
            },
            userName:{
                type:String,
                default:null
            },
            uniqueId:{
                type:String,
                default:null
            },
            avatar:{
                type:String,
                default:null
            },
            accountType:{
                type:String,
                default:null
            },
            accessToken:{
                type:String,
                default:null
            },
            show:{
                type:Boolean,
                default:true
            }
        }
    ],
    users:[
        {
            id:{
                type:String,
                default:null,
            },
            name:{
                type:String,
                default:null,
            },
            role:{
                type:String,
                default:null,
            },
            avatar:{
                type:String,
                default:null
            },
            email:{
                type:String,
                default:null
            }
        }
    ]

},{timestamps:true});

const Client = mongoose.Schema.Client || mongoose.model("Client",clientSchema);
export default Client;